name: windows-tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: Vampire/setup-wsl@v1
      with:
        additional-packages:
          dos2unix
    - name: Execute tests and generate coverage report
      shell: wsl-bash {0}
      env:
        RUNNING_ON_GITHUB_ACTIONS: true
      run: |
         find . -type f -print0 | xargs -0 -n 1 -P 4 dos2unix
         ./dev/tests/run_tests.sh
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
